#!/bin/sh

# get the value of a color from the current terminal color configuration
getTermColor() {
    echo -n "$( cat ~/.Xresources | grep  "$1" | head -n 1 | grep -oE "#[a-zA-Z0-9]{6}" | cut -c 2- )";
}

PANEL_FIFO=/tmp/panel-fifo
#PANEL_HEIGHT=26
PANEL_HEIGHT=23
PANEL_GAP=0
PANEL_FONT_FAMILY="gohufont:size=10"
ICON_FONT="FontAwesome:size=11"
ICON_FONT2="Source Han Sans JP Medium:size=9"
# ICON_FONT2="icomoon:size=11"

# System colors
s_main="252527"
s_second="3a3a3a"
s_third="545350"
s_fourth="3a3a3b"
s_fifth="e8e8f4"
s_fg="f6f9ff"
s_fg2="6f7277"

# BSPWM variables
# naming convention is b_<config_option>
b_border_width=8
b_window_gap=40
b_split_ratio=0.6
b_normal_border_color=#$s_main
b_active_border_color=#$s_second
b_focused_border_color=#$s_third
b_focused_locked_border_color=#$s_fourth
b_focused_sticky_border_color=#$s_fourth
b_focused_private_border_color=#$s_fourth
b_presel_border_color=#$s_fifth
b_urgent_border_color="#FFFFFF"

# Panel variables
PANEL_FIFO=/tmp/panel-fifo
export PANEL_HEIGHT=23
export PANEL_FONT_MAIN="gohufont:size=10"
export PANEL_FONT_ICON="FontAwesome:size=11"
export PANEL_FONT_ICON2="Source han Sans JP Medium:size=9"
export PANEL_GAP=0
export pPadding=1  # number of spaces to pad panel informaiton with

# variables for desktop area
export desktopDisplay=name     # [icon|name] - display desktop names or DO/DF variables.
export showFreeDesktops=true   # option to show nothing for free desktops
export desktopDisplayType=together # [together| separate] - show desktops in separate blocks or together in one block
# NoModeToggle=1 # if defined, no monocle/tiling toggle.

# desktop colors
export pUrgent="#ffffffff"
export pActive="#ff$s_third"
export pRest="#ff$s_second"

# Panel colors
export pBG="#ff$s_main"                     # Default background
export pFG="#ff$s_fg"                         # Default foreground
export pFG2="#ff$s_fg2"                         # second foreground
export pBGActiveTab="$pActive"                # Active title tab
export pBGInactiveTab="$pRest"                # Inactive title tab - also used to info.sh ouput background.
export pIcon="#ffaaaaaa"                      # color of icons from info.sh

# Workspace variables
export DO=$(echo -e '\uf0c8')  # occupied desktop
export DF=$(echo -e '\uf096')  # free desktop
export DT=$(echo -e '\uf009')  # tiling mode
export DM=$(echo -e '\uf0c9')  # monocle mode

# Separator for display items for info.sh
# form of the info.sh output is <pPadding><icon><content><pPadding><delim>
export delim="%{B$pBG} "

# options: mail yaourtUpdates mpd battery network volume weather clock themeSwitch
# If empty, all are used.
# it is possible to specify different information per monitor with barInfo<mon #>="options"
barInfo=""

# Customize options on different computers by hostname:
if [ "$HOSTNAME" = "littleapple" ]; then
    barInfo2="yaourtUpdates"
    barInfo1="themeSwitch volume clock"
    barInfo3="mpd clock"
fi

[ "$HOSTNAME" = "home2" ] && barInfo="battery network volume clock"

# Export panel variables - note - this doesn't work with dmenu_run, maybe because it's sourced a second layer down?
[ "$BSPWM_GAPS" = false ] && export PANEL_GAP=0

# dunst variables
DUNST_FONT="Dejavu Sans Mono 10"
